# Generated by Django 4.2.5 on 2023-10-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('Name', models.TextField(db_column='Name')),
            ],
            options={
                'db_table': 'Countries',
                'ordering': ['Id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('Id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('label', models.TextField(db_column='Label')),
                ('shortlabel', models.TextField(db_column='ShortLabel')),
                ('description', models.TextField(db_column='Description')),
                ('walletnumber', models.TextField(db_column='WalletNumber')),
                ('imageurl', models.TextField(db_column='ImageUrl')),
            ],
            options={
                'db_table': 'Currencies',
                'ordering': ['Id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countriesid', models.IntegerField()),
                ('currencyid', models.IntegerField()),
            ],
            options={
                'db_table': 'CurrencyCountry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Histories',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='UserId')),
                ('username', models.TextField(db_column='UserName')),
                ('userlogin', models.TextField(db_column='UserLogin')),
                ('idcurrency', models.IntegerField(db_column='IdCurrency')),
                ('datetime', models.DateTimeField(db_column='DateTime')),
                ('actiontype', models.IntegerField(db_column='ActionType')),
                ('idcountry', models.IntegerField(db_column='IdCountry')),
            ],
            options={
                'db_table': 'Histories',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
