# Generated by Django 4.2.5 on 2023-10-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segachange_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='histories',
            options={'managed': False},
        ),
    ]
